export const dummyProducts = [
  {
    id: "1",
    title: "Men's Casual T-Shirt",
    slug: "mens-casual-t-shirt",
    mrp: 29.99,
    salePrice: 19.99,
    percentOff: 33,
    thumbnail: "/images/product-01.jpg",
  },
  {
    id: "2",
    title: "Women's Running Shoes",
    slug: "womens-running-shoes",
    mrp: 79.99,
    salePrice: 59.99,
    percentOff: 25,
    thumbnail: "/images/product-02.jpg",
  },
  {
    id: "3",
    title: "Smartphone Case",
    slug: "smartphone-case",
    mrp: 14.99,
    salePrice: 9.99,
    percentOff: 33,
    thumbnail: "/images/product-03.jpg",
  },
  {
    id: "4",
    title: "Laptop Backpack",
    slug: "laptop-backpack",
    mrp: 49.99,
    salePrice: 39.99,
    percentOff: 20,
    thumbnail: "/images/product-04.jpg",
  },
  {
    id: "5",
    title: "Wireless Earbuds",
    slug: "wireless-earbuds",
    mrp: 59.99,
    salePrice: 49.99,
    percentOff: 17,
    thumbnail: "/images/product-05.jpg",
  },

  {
    id: "6",
    title: "Men's Casual T-Shirt",
    slug: "mens-casual-t-shirt",
    mrp: 29.99,
    salePrice: 19.99,
    percentOff: 33,
    thumbnail: "/images/product-06.jpg",
  },
  {
    id: "7",
    title: "Women's Running Shoes",
    slug: "womens-running-shoes",
    mrp: 79.99,
    salePrice: 59.99,
    percentOff: 25,
    thumbnail: "/images/product-07.jpg",
  },
  {
    id: "8",
    title: "Smartphone Case",
    slug: "smartphone-case",
    mrp: 14.99,
    salePrice: 9.99,
    percentOff: 33,
    thumbnail: "/images/product-08.jpg",
  },
  {
    id: "9",
    title: "Laptop Backpack",
    slug: "laptop-backpack",
    mrp: 49.99,
    salePrice: 39.99,
    percentOff: 20,
    thumbnail: "/images/product-09.jpg",
  },
  {
    id: "10",
    title: "Wireless Earbuds",
    slug: "wireless-earbuds",
    mrp: 59.99,
    salePrice: 49.99,
    percentOff: 17,
    thumbnail: "/images/product-10.jpg",
  },
];
